### ISSUE TITLE
JUnit report testsuites is not necessary

### ISSUE THREAD

**Issue by 264768502** [gastlygem/junitparser#1]
When read a junit report, which don't contain testsuites (only contain testsuite, it is also valid junit report), but it cannot work with this parser because it will check testsuites first

**Comment by gastlygem** [comment]
Fixed. Note that the usage is a bit different because the result is actually an instance of `TestSuite`, and the usage will be like this:

```python
result = JUnitXml.fromfile('junit.xml')
for case in result:
    print(case.name)
for property in result.properties():
    ...
```
Tell me if it suites your need.
