### ISSUE TITLE
Error when importing IntAttr

### ISSUE THREAD

**Issue by Alex-Mann** [gastlygem/junitparser#10]
I'm trying to import IntAttr to add a custom attribute, but python is complaining that `ImportError: cannot import name 'IntAttr'`.

Any ideas?

**Comment by gastlygem** [comment]
Sorry I forgot to implement it 🤦‍♂️ 

I've just updated the package. Try install 1.2.1 and see if it works.

**Comment by gastlygem** [comment]
Fixed with 1.2.1 release.
