### ISSUE TITLE
lacking documentation on base classes

### ISSUE THREAD

**Issue by dcgudeman** [gastlygem/junitparser#14]
I am trying to use this library to parse the results of our integration tests but there is basically no documentation on the base class(es) (Element). Some basic documentation on the properties of objects like **TestSuite**, **TestCase** and **Result** would be great. Nonetheless, great library 👍.

**Comment by gastlygem** [comment]
Thanks for suggesting. Will Totally do that!

**Comment by nd842** [comment]
+1

**Comment by gastlygem** [comment]
I've added docstrings in the code and now they could be read with pydoc or any IDE.
