### ISSUE TITLE
Parser fails if the tag  `testsuites` is not present

### ISSUE THREAD

**Issue by yhoazk** [gastlygem/junitparser#17]
Taking as example the generated xml from [nose2](https://nose2.readthedocs.io/en/latest/plugins/junitxml.html#sample-output), and the snippet from the readme:
```py
from junitparser import JUnitXml

xml = JUnitXml.fromfile('sample.xml')
for suite in xml:
    print("Test suite name: {}".format(suite.name))
    for case in suite:
        print("Test case name: {}".format(case.name))
```
An exception is thrown:
```
Test suite name: test_gen:1
Traceback (most recent call last):
  File "read_xml.py", line 8, in <module>
    for case in suite:
TypeError: 'TestCase' object is not iterable
```

**Expected result**: The missing tag `testsuites` should not affect the parsing or should be handled gracefully if not supported.

**Comment by gastlygem** [comment]
The assumption is that if the file contains just one test suite(whether `testsuites` exists or not), it will enumerate from within that suite, so the code should be:

`
suite = JUnitXml.fromfile('sample.xml')
for case in suite:
    print("Test case name: {}".format(case.name))
`
