### ISSUE TITLE
Support python2 - open for contributions?

### ISSUE THREAD

**Issue by SteinHeselmans** [gastlygem/junitparser#2]
For the scope of https://github.com/melexis/warnings-plugin/issues/20, we are considering to use this junitparser for parsing failures from a JUnit xml file set.

I read that python2 is not supported in your readme. Would you be open to accept our contributions for supporting python2? Or is there a definite reason to not support it?

I couldn't find your email, so therefore this issue to ask the question.

**Comment by SteinHeselmans** [comment]
On first sight the metaclass syntax is different py2 to py3, where http://python-future.org/compatible_idioms.html#metaclasses might give a solution. I didn't spend effort yet to try it, but should work. 

Don't know if or how many problems we'll encounter doing the port, but we're open to contribute this.

**Comment by gastlygem** [comment]
I see no reason not supporting Python 2. It's just that I had the fortune to work with the newest Python. I might add Python 2 support myself but it might take some time, but I'd love to see your pull requests :)
