### ISSUE TITLE
Merging test files doesn't merge test counts

### ISSUE THREAD

**Issue by andydawkins** [gastlygem/junitparser#21]
I have two junit xml files.  One for two different test suites run in parallel during my CI

I'm merging the resulting test xml files using junitparser to a single file in order to list the results in the CI 

When I merge the files with the following testsuite results....
`<testsuite errors="0" failures="0" name="pytest" skips="0" tests="16" time="43.390">`
and
`<testsuite errors="0" failures="0" name="pytest" skips="0" tests="14" time="15.434">`

the resulting merged output is
`<testsuites errors="0" failures="0" tests="0" time="0">`

Note the plural 'testsuites', this does not contain any 'testsuite' elements.
Also note that the tests and time have not been summed as I would expect.

**Comment by andydawkins** [comment]
I have submitted a fix for this issue here...
#22

**Comment by gastlygem** [comment]
Merged. Thanks!
