### ISSUE TITLE
RFC: XML with and without <testsuites> tag

### ISSUE THREAD

**Issue by atodorov** [gastlygem/junitparser#24]
Hello,
in Kiwi TCMS we are seeing failures parsing different XML files. The main difference is that some of them contain `<testsuites>` tag while others don't, see:
https://github.com/kiwitcms/junit.xml-plugin/issues/9

What would be a good way to discover the varying formats so we can adjust our parsing tools?

**Comment by gastlygem** [comment]
Sorry for not seeing this earlier. This library is just a wrapper over an xml file for easy processing.  What I can think of is something similar to the last comment in the thread you posted:

```
if xml._tag == "testsuites":
  cases = [case for cases in xml for case in cases]
else:
  cases = list(xml)
``` 

But I'm open to suggestions.
