### ISSUE TITLE
Bug in result class (use of type instead of type_)

### ISSUE THREAD

**Issue by dries007** [gastlygem/junitparser#35]
Hi, I stumbled across this while working on a project:

https://github.com/gastlygem/junitparser/blob/6267a27c4dcdd07173b3a73f3949808045b0b846/junitparser/junitparser.py#L550-L555

I think this is supposed to be `if type_:` instead of `if type:`, since now it's always true.

Kind regards,
Dries

**Comment by gastlygem** [comment]
It's been fixed. Thanks!
