### ISSUE TITLE
Get properties of testcase

### ISSUE THREAD

**Issue by NINI1988** [gastlygem/junitparser#37]
When I use googletest to export the test result, we add requirement numbers to the testcases with the function `RecordProperty`. 
How is it possible to get the property list of a testcase?
I see only testsuite has a properties() function.

This is a small example:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="1" failures="0" disabled="0" errors="0" timestamp="2020-02-27T10:30:10" time="1.218" name="AllTests">
  <testsuite name="testSuite" tests="1" failures="0" disabled="0" errors="0" time="0.925">
    <testcase name="test" status="run" time="0" classname="testSuite">
      <properties>
        <property name="req" value="requirement12"/>
      </properties>
    </testcase>
  </testsuite>
</testsuites>
```

**Comment by gastlygem** [comment]
Please check `Handling XML with custom element` in the documentation. See if it works for you.

**Comment by NINI1988** [comment]
Thanks for your reply. Yes it works with the custom handling, but I thought properties in a testcase is a standard field which many users will have?

**Comment by gastlygem** [comment]
In fact this is the first time I see property defined in a testcase. 

JUnit is a loose standard and test tools could come up with their own unique extensions. I used the Jenkins JUnit format as reference because it appears to be the most basic.

**Comment by jayjoshi-crest** [comment]
@gastlygem Any plan to include this functionality? We have a plugin generating tests with properties and we'll need the properties to be parsed by junitparser.

**Comment by FelixDuvalletKodiak** [comment]
I am also looking for this functionality.

One use case is to parse the output from `googletest`, which allows recording [custom properties][1] to test suites or test cases.

[1]: https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#logging-additional-information

**Comment by gastlygem** [comment]
#39 implements properties for TestCase thanks to @aopincar 

Please try it out with version 1.5.0

**Comment by gastlygem** [comment]
@jayjoshi-crest @FelixDuvalletKodiak Supporting different flavors isn't in current scope. However it could be done relative easily with the following code:

```python
from junitparser import JUnitXml, Properties

properties = Properties()

xml = JUnitXml.fromfile("junit.xml")
for suite in xml:
    for case in suite:
        # Update case so it can have properties
        case.append(properties)
        # Access properties
        props = case.child(Properties)
        # Access each property
        for prop in props:
            # Do your thing with each property
```

**Comment by FelixDuvalletKodiak** [comment]
@gastlygem Thanks for posting this code example, it's very helpful and I confirm that it works for `googletest`'s test properties.

This satisfies my use case (and many others, I imagine).
