### ISSUE TITLE
junitparser -v outputs the version of argparse, not junitparser

### ISSUE THREAD

**Issue by serhiy-storchaka** [gastlygem/junitparser#43]
`junitparser -v` outputs the version of `argparse`, not the version of `junitparser`.

`argparse.__version__` is currently equal to `'1.1'` and was not changed many years (despite the changes in the module itself). It is planned for removing in future Python versions.

**Comment by gastlygem** [comment]
Hi Serhiy,

Thanks for reporting. I fixed it in the 1.4.2 release.

Cheers
